### ISSUE TITLE
Problem found during testing!

### ISSUE THREAD

**Issue by kslim99** [swsnu/swpp2020-team10#18]
Enzyme does't support React v17. What should we do?

**Comment by gratus907** [comment]
https://www.npmjs.com/package/@wojtekmaj/enzyme-adapter-react-17
This issue [link](https://github.com/enzymejs/enzyme/issues/2429) seems relevant.
There are some unofficial enzyme-adapter, though I am not sure if we should use this or not. It might cause some problems.

**Comment by Jong25** [comment]
I think just downgrading to React v16 would enough, since we're not using features related to v17.
But we need some testing after downgrading I guess.
