### ISSUE TITLE
[Peer Testing] bug report

### ISSUE THREAD

**Issue by Jong25** [swsnu/swpp2020-team10#48]
아래에 작성해주세요!
감사합니다!

+)
냉장고 재료 관련해서 구현이 아직 부족합니다.
냉장고에 재료를 추가할 때 type은 공란으로 남겨주세요!
이 부분 추후에 수정할 예정입니다. 양해 부탁드립니다ㅠㅠ

**Comment by creambread-duck** [comment]
![image](https://user-images.githubusercontent.com/70693762/101758532-c9291280-3b1b-11eb-9b43-650ff079841c.png)
submit을 누르니 반응이 없습니다...

**Comment by shapespeare** [comment]
![image](https://user-images.githubusercontent.com/26834464/101758610-e1009680-3b1b-11eb-8b92-3b662498f9ad.png)

추가가 안 되네요

**Comment by GooJinSun** [comment]
![image](https://user-images.githubusercontent.com/37523788/101760083-bc0d2300-3b1d-11eb-9998-7e1602602c09.png)
냉장고에 재료를 추가하면 나타나는 이미지는 무슨 관련이 있는건가요??

**Comment by junepaykim** [comment]
![20201210192655](https://user-images.githubusercontent.com/49562343/101760032-adbf0700-3b1d-11eb-99e9-06b89ac9b792.png)
아이템 추가가 되지 않았습니다.

**Comment by ssm0318** [comment]
이거 칼로리 진짜인가요??? ㄷㄷ
<img width="803" alt="스크린샷 2020-12-10 오후 7 27 53" src="https://user-images.githubusercontent.com/25769209/101760137-d47d3d80-3b1d-11eb-9e1b-a0b1a9161181.png">

**Comment by ssm0318** [comment]
<img width="151" alt="스크린샷 2020-12-10 오후 7 28 48" src="https://user-images.githubusercontent.com/25769209/101760204-eeb71b80-3b1d-11eb-81cf-8c906929018b.png">
사소한거지만 앱 이름을 설정해주시는 것도 좋을 것 같아요!
전반적으로 외국 서비스 같고 신기하고 예쁘네요~~

**Comment by ihatedebug** [comment]
![image](https://user-images.githubusercontent.com/57564205/101760240-f8d91a00-3b1d-11eb-8cb7-157a84982929.png)
![image](https://user-images.githubusercontent.com/57564205/101760249-fb3b7400-3b1d-11eb-848c-0364c9e6e6fd.png)
검색이 안되는거 같은데 맞나요?

**Comment by snusun** [comment]
![image](https://user-images.githubusercontent.com/60461200/101760029-ad267080-3b1d-11eb-9b4b-43aadb4bc1d6.png)
singup 할때 email regex를 하시면 좋을 것 같아요! 지금은 'test'라고만 입력해도 가입이 되네요.

**Comment by junhyekh** [comment]
뒤로 갈 수 있는 버튼이나 nav bar같은게 추가되면 사용하기 더 편할것 같습니다

**Comment by curious-curie** [comment]
* 회원가입 시 쓸 수 있는 기능들 UI적으로 아예 안보이게 하지 않고 표시해둔게 너무 좋은 것 같아요! 
![image](https://user-images.githubusercontent.com/47528556/101760004-a566cc00-3b1d-11eb-99a7-e3b63aa3fc10.png)
* 회원가입 하구 바로 로그인 되거나 로그인 페이지로 리다이렉트 되면 좋을 것 같아요
* 메인 페이지에 recommendation이 더  많이 있었으면 좋겠어요! 

* 냉장고에 어떻게 넣을 수 있나요?? add한다음에 apple 치면 500 에러가 나던데 ! 재료가 자동완성이 되거나 어떻게 넣는건지 안내가 있으면 좋을 것 같아요

**Comment by gratus907** [comment]
# 답변
- @junepaykim  @creambread-duck  @shapespeare Type은 *반드시* 공란으로 해주세요. 차후 수정 예정입니다.
- @GooJinSun  image는 type과 함께 수정될 예정입니다. Type에 관련된 문제입니다.
- @ssm0318 Calories는 per serving으로 나눠야 하는데 저희도 방금 발견했습니다. /24 해야 합니다.

**Comment by Jeseong-Jeong** [comment]
냉장고의 음식들과 레시피를 연결해주는 기능이 있나요?

**Comment by janejane516** [comment]
추천된 음식에 후기를 달면 후기 페이지로 redirect되지 않는 점이 조금 의문이었습니다!

**Comment by ssm0318** [comment]
<img width="796" alt="스크린샷 2020-12-10 오후 7 31 00" src="https://user-images.githubusercontent.com/25769209/101760469-3dfd4c00-3b1e-11eb-9e4d-f87e7c08dfd8.png">
이거 흰색 줄은 디자인인가요? form인줄 알고 계속 클릭하게 되는데 저만 그랬을지도 몰라요 ㅎㅎ

**Comment by koyrkr** [comment]
코멘트입니다! 

- 비밀번호 조건이 무엇인가요? 명확히 안나와있어서 계속 Invalid Password라고 뜹니다 ㅠㅠ 숫자나 기호가 들어가면 안되는 것같기도 합니다..!
- delete 할때 alert가 있으면 좋을 것 같아요!
- UI가 심플해서 직관적인 것 같아요! 
- sign up 하고 login 창으로 어떻게 돌아가나요? 돌아가지 못하는 것 같습니다!
- 사진과 매치가 안되는 재료가 있는 것 같습니다
![image](https://user-images.githubusercontent.com/42240753/101760492-4786b400-3b1e-11eb-8120-16a5045bd9de.png)

**Comment by junhyekh** [comment]
<img width="351" alt="스크린샷 2020-12-10 오후 7 33 55" src="https://user-images.githubusercontent.com/70698100/101760791-ac420e80-3b1e-11eb-9a7d-3e391c656757.png">
레코멘데이션에서 레이팅이나 선호 버튼이 클릭은 되는데 반영 안되어서 혹시 의도하신건지 궁금합니다

**Comment by fjqlddb06** [comment]
![image](https://user-images.githubusercontent.com/24264246/101760872-cd0a6400-3b1e-11eb-932b-75c2c3841a31.png)
별을 실수로 한번 누른 후 평점을 바꿀 수 없다는게 너무 불안한거 같습니다.

**Comment by gratus907** [comment]
## 답변
모두 좋은 의견 주셔서 너무 감사드립니다~!!! 몇가지 여쭤보신점에 대해 답변을 더 드립니다. 

- @Jeseong-Jeong @curious-curie Type을 통해 재료가 어떤 음식인지 확인하고 이를 반영할 예정입니다. 
- @koyrkr 사진은 type과 함께 수정될 예정입니다.
- @snusun 추천 레시피에 대한 좋아요/싫어요는 추천 알고리즘에 반영되어 다음 추천에 영향을 미치게 됩니다. 

지금 보고 계신 추천은 이전 추천에 대한 좋아요/싫어요가 반영되고 있는 결과입니다. 레시피의 수가 많아서 반영을 체감하기 위해 조금 많은 횟수의 좋아요/싫어요가 필요한 것 같습니다.

**Comment by fjqlddb06** [comment]
![image](https://user-images.githubusercontent.com/24264246/101761296-4d30c980-3b1f-11eb-9be5-70cb7505944c.png)
조리 순서를 좀 더 보기 좋게 배열 했으면 좋겠습니다.
그리고 다른 사람의 리뷰는 못보는 건가요?

**Comment by kslim99** [comment]
저도 답변을 조금 드리겠습니다. 

@fjqlddb06 거기에 나오는 rating은 현재 그 레시피의 rating으로, 그 recipe를 클릭하셔서 detail page로 들어가시면 평점을 남기실 수 있습니다. 그리고 현재 리뷰 수가 적어 그 레시피에 다른 사람의 리뷰가 안 달린 것입니다.

모두들 좋은 의견 감사드립니다 ㅎㅎ
